name: cmake

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-12]

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies on Linux
      run: |
           sudo apt-get install ninja-build -y
           cmake --version
      if: runner.os == 'Linux'
      
    - name: Install dependencies on macOS
      run: |
           brew install giflib
           brew install ninja
           cmake --version
      if: runner.os == 'macOS'
        

    - name: configure
      run: cmake -Bbuild -G Ninja -DSW_BUILD=OFF -DBUILD_PROG=OFF -DBUILD_SHARED_LIBS=ON


    - name: build
      run: sudo cmake --build build --config Release --target install
